"""Offline model trainer for AI trading modules.

Run this BEFORE starting the bot to pre-train models on historical data.
Usage:
    python -m engine.trainer --config config.json --datadir user_data/data
"""

import argparse
import logging
from pathlib import Path

import pandas as pd
from pandas import DataFrame, to_datetime

from engine.direction_predictor import DirectionPredictor
from engine.features import FeatureEngineer
from engine.regime_classifier import RegimeClassifier

logger = logging.getLogger(__name__)


def load_historical_data(datadir: str, pair: str, timeframe: str = "4h") -> DataFrame:
    """Load OHLCV data from freqtrade's data directory.

    Also handles the case where data is stored in flat feather files
    in the okx/ subdirectory (generated by freqtrade download-data).

    freqtrade is optional: if not installed, falls back to directly reading
    feather/csv files. This lets the standalone engine train without freqtrade.
    """
    from pathlib import Path

    data_path = Path(datadir)
    if not data_path.is_absolute():
        data_path = Path.cwd() / data_path

    # Try loading via freqtrade's native loader (subdirectory structure)
    try:
        from freqtrade.data.history import load_pair_history
    except ImportError:
        load_pair_history = None  # freqtrade not installed — use direct file read
        logger.debug("freqtrade not installed; using direct feather/csv read")

    if load_pair_history is not None:
        for data_format in ["feather", "json"]:
            try:
                df = load_pair_history(
                    pair=pair,
                    timeframe=timeframe,
                    datadir=data_path,
                    data_format=data_format,
                    timerange=None,
                    candle_type="futures",
                )
                if df is not None and len(df) > 100:
                    logger.info(f"Loaded {len(df)} candles for {pair} ({data_format})")
                    return df
            except Exception as e:
                logger.debug(f"Could not load {pair} via freqtrade loader: {e}")

    # Fallback: directly read feather/csv files in okx/ subdirectory
    # File naming: {PAIR_BASE}_{PAIR_QUOTE}_{PAIR_SETTLE}-{timeframe}-futures.feather
    safe_pair = pair.replace("/", "_").replace(":", "_")
    for data_dir in [data_path, data_path / "okx", data_path / "binance"]:
        for ext, reader in (("feather", pd.read_feather), ("csv", pd.read_csv)):
            file_path = data_dir / f"{safe_pair}-{timeframe}-futures.{ext}"
            if file_path.exists():
                df = reader(file_path)
                if len(df) > 100:
                    logger.info(f"Loaded {len(df)} candles for {pair} from {file_path}")
                    return df

    raise FileNotFoundError(
        f"No historical data for {pair} at {datadir}. "
        f"Place a feather/csv file named {safe_pair}-{timeframe}-futures.feather "
        f"under {data_path}/okx/ (or {data_path}/binance/)."
    )


def load_derivatives_data(datadir: str, pair: str, timeframe: str = "1h") -> "DataFrame | None":
    """Load derivatives (funding/OI/long-short) feather for a pair.

    Returns None (not an error) if the file is absent — derivatives are an
    optional enhancement. When absent, training falls back to OHLCV-only.
    """
    safe_pair = pair.replace("/", "_").replace(":", "_")
    data_path = Path(datadir)
    if not data_path.is_absolute():
        data_path = Path.cwd() / data_path

    for data_dir in [data_path, data_path / "okx", data_path / "binance"]:
        for ext, reader in (("feather", pd.read_feather), ("csv", pd.read_csv)):
            file_path = data_dir / f"{safe_pair}-derivatives-{timeframe}-futures.{ext}"
            if file_path.exists():
                df = reader(file_path)
                if len(df) > 0:
                    logger.info(f"Loaded {len(df)} derivatives rows for {pair} from {file_path}")
                    return df
    logger.debug(f"No derivatives data for {pair} — OHLCV-only mode")
    return None


def train_models(
    datadir: str,
    pairs: list[str] = None,
    model_dir: str = "./models",
    timeframe: str = "4h",
    regime_horizon: int = 6,
    direction_horizon: int = 4,
    use_derivatives: bool = False,
) -> dict:
    """Train all AI models on historical data.

    Args:
        use_derivatives: If True, load {pair}-derivatives-{tf}-futures.feather
            and merge funding/OI/long-short time-series features. Missing
            files are skipped gracefully (pair falls back to OHLCV-only).

    Returns:
        dict with training metrics per pair.
    """
    if pairs is None:
        pairs = ["BTC/USDT:USDT", "ETH/USDT:USDT"]

    fe = FeatureEngineer()
    results = {}

    # Combine data from all pairs
    all_features = []
    for pair in pairs:
        try:
            ohlcv = load_historical_data(datadir, pair, timeframe=timeframe)
        except FileNotFoundError as e:
            logger.warning(str(e))
            continue

        derivatives = load_derivatives_data(datadir, pair, timeframe=timeframe) if use_derivatives else None
        if derivatives is not None:
            features = fe.compute_all_features(ohlcv, derivatives)
            logger.info(f"Features (OHLCV+deriv) computed for {pair}: {len(features)} rows, {len(features.columns)} cols")
        else:
            features = fe.compute_price_features(ohlcv)
            logger.info(f"Features computed for {pair}: {len(features)} rows")
        all_features.append(features)

    if not all_features:
        raise RuntimeError("No training data available. Place feather/csv files under datadir/okx/.")

    combined = pd.concat(all_features)
    logger.info(f"Total training data: {len(combined)} rows")

    # Train regime classifier (label_horizon removes same-instant leakage)
    regime_clf = RegimeClassifier(model_dir=model_dir)
    regime_metrics = regime_clf.train(combined, label_horizon=regime_horizon)
    results["regime_classifier"] = regime_metrics
    logger.info(f"Regime classifier: accuracy={regime_metrics['accuracy']:.3f}")

    # Train direction predictor (multi-candle horizon for a learnable signal)
    dir_pred = DirectionPredictor(model_dir=model_dir)
    dir_metrics = dir_pred.train(combined, horizon=direction_horizon)
    results["direction_predictor"] = dir_metrics
    logger.info(f"Direction predictor: RMSE={dir_metrics['rmse']:.5f}, dir_acc={dir_metrics['direction_accuracy']:.3f}")

    logger.info(f"Models saved to {model_dir}/")
    return results


def main():
    parser = argparse.ArgumentParser(description="Train AI trading models")
    parser.add_argument("--config", default="config.json", help="Config file path")
    parser.add_argument("--datadir", default="user_data/data", help="Data directory")
    parser.add_argument("--pairs", nargs="*", default=None, help="Trading pairs")
    parser.add_argument("--model-dir", default="./models", help="Model output directory")
    parser.add_argument("--timeframe", default="4h", help="OHLCV timeframe (e.g. 1h, 4h)")
    parser.add_argument("--derivatives", action="store_true",
                        help="Load {pair}-derivatives-{tf}-futures.feather and merge funding/OI/LS features")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    results = train_models(
        datadir=args.datadir,
        pairs=args.pairs,
        model_dir=args.model_dir,
        timeframe=args.timeframe,
        use_derivatives=args.derivatives,
    )

    print("\n=== Training Results ===")
    for model, metrics in results.items():
        print(f"{model}: {metrics}")


if __name__ == "__main__":
    main()
