"""Offline model trainer for AI trading modules.

Run this BEFORE starting the bot to pre-train models on historical data.
Usage:
    python -m engine.trainer --config config.json --datadir user_data/data
"""

import argparse
import logging
from pathlib import Path

import pandas as pd
from pandas import DataFrame, to_datetime

from engine.direction_predictor import DirectionPredictor
from engine.features import FeatureEngineer
from engine.regime_classifier import RegimeClassifier

logger = logging.getLogger(__name__)


def load_historical_data(datadir: str, pair: str, timeframe: str = "4h") -> DataFrame:
    """Load OHLCV data from freqtrade's data directory.

    Also handles the case where data is stored in flat feather files
    in the okx/ subdirectory (generated by freqtrade download-data).
    """
    from pathlib import Path
    from freqtrade.data.history import load_pair_history

    data_path = Path(datadir)
    if not data_path.is_absolute():
        data_path = Path.cwd() / data_path

    # Try loading via freqtrade's native loader (subdirectory structure)
    for data_format in ["feather", "json"]:
        try:
            df = load_pair_history(
                pair=pair,
                timeframe=timeframe,
                datadir=data_path,
                data_format=data_format,
                timerange=None,
                candle_type="futures",
            )
            if df is not None and len(df) > 100:
                logger.info(f"Loaded {len(df)} candles for {pair} ({data_format})")
                return df
        except Exception as e:
            logger.debug(f"Could not load {pair} via freqtrade loader: {e}")

    # Fallback: directly read feather files in okx/ subdirectory
    # File naming: {PAIR_BASE}_{PAIR_QUOTE}_{PAIR_SETTLE}-{timeframe}-futures.feather
    safe_pair = pair.replace("/", "_").replace(":", "_")
    for data_dir in [data_path, data_path / "okx", data_path / "binance"]:
        feather_path = data_dir / f"{safe_pair}-{timeframe}-futures.feather"
        if feather_path.exists():
            df = pd.read_feather(feather_path)
            if len(df) > 100:
                logger.info(f"Loaded {len(df)} candles for {pair} from {feather_path}")
                return df

    raise FileNotFoundError(
        f"No historical data for {pair} at {datadir}. "
        f"Run: freqtrade download-data -c config.json --pairs {pair} "
        f"--timeframes {timeframe} --trading-mode futures"
    )


def train_models(
    datadir: str,
    pairs: list[str] = None,
    model_dir: str = "./models",
) -> dict:
    """Train all AI models on historical data.

    Returns:
        dict with training metrics per pair.
    """
    if pairs is None:
        pairs = ["BTC/USDT:USDT", "ETH/USDT:USDT"]

    fe = FeatureEngineer()
    results = {}

    # Combine data from all pairs
    all_features = []
    for pair in pairs:
        try:
            ohlcv = load_historical_data(datadir, pair)
            features = fe.compute_price_features(ohlcv)
            all_features.append(features)
            logger.info(f"Features computed for {pair}: {len(features)} rows")
        except FileNotFoundError as e:
            logger.warning(str(e))
            continue

    if not all_features:
        raise RuntimeError("No training data available. Run `freqtrade download-data` first.")

    combined = pd.concat(all_features)
    logger.info(f"Total training data: {len(combined)} rows")

    # Train regime classifier
    regime_clf = RegimeClassifier(model_dir=model_dir)
    regime_metrics = regime_clf.train(combined)
    results["regime_classifier"] = regime_metrics
    logger.info(f"Regime classifier: accuracy={regime_metrics['accuracy']:.3f}")

    # Train direction predictor
    dir_pred = DirectionPredictor(model_dir=model_dir)
    dir_metrics = dir_pred.train(combined)
    results["direction_predictor"] = dir_metrics
    logger.info(f"Direction predictor: RMSE={dir_metrics['rmse']:.5f}, dir_acc={dir_metrics['direction_accuracy']:.3f}")

    logger.info(f"Models saved to {model_dir}/")
    return results


def main():
    parser = argparse.ArgumentParser(description="Train AI trading models")
    parser.add_argument("--config", default="config.json", help="Config file path")
    parser.add_argument("--datadir", default="user_data/data", help="Data directory")
    parser.add_argument("--pairs", nargs="*", default=None, help="Trading pairs")
    parser.add_argument("--model-dir", default="./models", help="Model output directory")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    results = train_models(
        datadir=args.datadir,
        pairs=args.pairs,
        model_dir=args.model_dir,
    )

    print("\n=== Training Results ===")
    for model, metrics in results.items():
        print(f"{model}: {metrics}")


if __name__ == "__main__":
    main()
